version: '3'
services:
  
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: "cinema"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"

  web:
    build: ./
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic &&
                    gunicorn web.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - /web_django
    expose:
      - 8000
    restart: "on-failure"
    depends_on:
      - postgres
