version: '3'
services:
  
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=feelinMSSQL_2024

  web:
    build: ./
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic &&
                    gunicorn web.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - /web_django
    expose:
      - 8000
    restart: "on-failure"
    depends_on:
      - mssql
