version: '3'
services:
  
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: "cinema"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"

  web:
    build:
      dockerfile: ./Dockerfile
      context: ./
    command: sh -c "python manage.py runserver"
    volumes:
      - /web_django
    expose:
      - 8000
    restart: "on-failure"
    depends_on:
      - mssql
